### ISSUE TITLE
how to config ssl_client_certificate ssl/ca.crt; 

### ISSUE THREAD

**Issue by songlong** [baidu/bfe#105]
when using tls certificate, how to config client client public key certificate like nginx ssl_client_certificate ssl/ca.crt;

**Comment by xiaofei0800** [comment]
Client Authentication is configured in tls_rule_conf.data. 
Example: 
{
    "Version": "12",
    "DefaultNextProtos": ["http/1.1"],
    "Config": {
        "example_product": {
            "VipConf": [
                "10.199.4.14"
            ],
            "SniConf": null,
            "CertName": "example.org",
            "NextProtos": [
                "http/1.1"
            ],
            "Grade": "C",
            "ClientAuth": true,
            "ClientCAName": "example_client_ca"
        }
    }
}
The CA certificate file is "example_client_ca.crt" under ClientCABaseDir configed in bfe.conf HttpsBasic part. 
The suffix of client CA certificate file is fixed to ".crt" and there is no need to take it to "ClientCAName".
