### ISSUE TITLE
bfe 之前使用了 "车轮大战" 架构，避免 GC （STW） 停顿。现在还是吗？

### ISSUE THREAD

**Issue by aixiaoxiang** [baidu/bfe#108]
bfe 之前使用了 "车轮大战" 架构，避免 GC 停顿。现在还是吗？

![image](https://user-images.githubusercontent.com/8416556/69226723-9122fa80-0bbb-11ea-9fc1-40edcb51a45d.png)

![image](https://user-images.githubusercontent.com/8416556/69226737-9aac6280-0bbb-11ea-90fb-91d9c125a3b4.png)

**Comment by iyangsj** [comment]
仅基于go早期版本编译时基于该方案规避gc延迟影响

**Comment by aixiaoxiang** [comment]
> 仅基于go早期版本编译时基于该方案规避gc延迟影响

嗯，现在 go 的gc延时已经很低了。
