### ISSUE TITLE
安装不了，timeout

### ISSUE THREAD

**Issue by willzhujian** [baidu/bfe#128]
https://www.bfe-networks.net/ 官网上面的两种安装方式都安装不了
1.源码安装，make报下面错误

make
go: github.com/asergeyev/nradix@v0.0.0-20170505151046-3872ab85bb56: Get https://proxy.golang.org/github.com/asergeyev/nradix/@v/v0.0.0-20170505151046-3872ab85bb56.mod: dial tcp 216.58.200.241:443: i/o timeout
go get golang.org/x/tools/cmd/goyacc
go: github.com/asergeyev/nradix@v0.0.0-20170505151046-3872ab85bb56: Get https://proxy.golang.org/github.com/asergeyev/nradix/@v/v0.0.0-20170505151046-3872ab85bb56.mod: dial tcp 172.217.24.17:443: i/o timeout
make: *** [prepare-dep] 错误 1

2.go get安装，报下面错误

go get github.com/baidu/bfe
package golang.org/x/crypto/chacha20poly1305: unrecognized import path "golang.org/x/crypto/chacha20poly1305" (https fetch: Get https://golang.org/x/crypto/chacha20poly1305?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/crypto/ocsp: unrecognized import path "golang.org/x/crypto/ocsp" (https fetch: Get https://golang.org/x/crypto/ocsp?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/sys/unix: unrecognized import path "golang.org/x/sys/unix" (https fetch: Get https://golang.org/x/sys/unix?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/net/websocket: unrecognized import path "golang.org/x/net/websocket" (https fetch: Get https://golang.org/x/net/websocket?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

**Comment by zops** [comment]
向Go这种，提供源码编译的前提下，应该也提供编译好的二进制命令包，否则就因为被墙这种问题会阻止很多人去体验。主要是百度技术内部很多都不注重细节，所以这些小细节就是有能力就体验一下，没能力看看就行了

**Comment by iyangsj** [comment]
@willzhujian 
你的环境无法访问golang.org, 建议先设置代理：
export GOPROXY=https://goproxy.io

@zops 
感谢建议，后续会支持二进制包下载安装及基于snap一键安装
