### ISSUE TITLE
Support Mac OS

### ISSUE THREAD

**Issue by weixiao619** [baidu/bfe#131]
**Describe the bug**
test case error

**Screenshots**
--- FAIL: TestServer_Exceed_Max_Concurrent_Streams (0.11s)
    server_test.go:1312: client writing Frame should fail
--- FAIL: TestServer_Read_First_Request_Header_Timeout (1.21s)
    server_test.go:1324: client writing Frame should fail
2019-11-28 15:30:39.570766 +0800 CST m=+2.538249710: writing id 3 frame to server
--- FAIL: TestServer_Read_Client_Again_Timeout (2.52s)
    server_test.go:1390: 2019-11-28 15:30:41.578595 +0800 CST m=+4.546032901: client writing Frame should fail
FAIL
coverage: 77.7% of statements
FAIL	github.com/baidu/bfe/bfe_spdy	4.566s
ok  	github.com/baidu/bfe/bfe_stream	(cached)	coverage: 90.8% of statements
ok  	github.com/baidu/bfe/bfe_tls	(cached)	coverage: 77.8% of statements
ok  	github.com/baidu/bfe/bfe_util	(cached)	coverage: 12.0% of statements
?   	github.com/baidu/bfe/bfe_util/access_log	[no test files]
ok  	github.com/baidu/bfe/bfe_util/bns	(cached)	coverage: 66.7% of statements
ok  	github.com/baidu/bfe/bfe_util/byte_pool	(cached)	coverage: 100.0% of statements
ok  	github.com/baidu/bfe/bfe_util/hash_set	(cached)	coverage: 90.6% of statements
ok  	github.com/baidu/bfe/bfe_util/ipdict	(cached)	coverage: 87.6% of statements
ok  	github.com/baidu/bfe/bfe_util/ipdict/txt_load	(cached)	coverage: 81.8% of statements
ok  	github.com/baidu/bfe/bfe_util/net_util	(cached)	coverage: 37.4% of statements
ok  	github.com/baidu/bfe/bfe_util/pipe	(cached)	coverage: 66.7% of statements
ok  	github.com/baidu/bfe/bfe_util/signal_table	(cached)	coverage: 31.2% of statements
ok  	github.com/baidu/bfe/bfe_websocket	(cached)	coverage: 86.4% of statements
FAIL
make: *** [test-case] Error 1

**Additional context**

**Comment by weixiao619** [comment]
can't support macOS？

**Comment by iyangsj** [comment]
Currently only Linux is supported. Mac/Windows will be supported in future version.

**Comment by iyangsj** [comment]
#190
