### ISSUE TITLE
数据配置热加载功能怎么开启？

### ISSUE THREAD

**Issue by willzhujian** [baidu/bfe#132]
是分自动和手动吗？
![image](https://user-images.githubusercontent.com/54895023/69842195-4d0bb600-129d-11ea-9242-150fc063af2b.png)

这个功能怎么开启

**Comment by willzhujian** [comment]
还有文档中：

子集群内的负载均衡
在同一子集群内的多个实例间，BFE支持使用多种负载均衡算法：
WRR: 加权轮询算法
WLC: 加权最小连接数

这个配置没找到在哪里？

**Comment by iyangsj** [comment]
> 是分自动和手动吗？
> ![image](https://user-images.githubusercontent.com/54895023/69842195-4d0bb600-129d-11ea-9242-150fc063af2b.png)
> 
> 这个功能怎么开启

在**本机**执行reload请求，例如：热加载rewrite规则配置
curl http://localhost:8421/reload/mod_rewrite

相关文档说明在v0.5.0完善

**Comment by iyangsj** [comment]
> 还有文档中：
> 
> 子集群内的负载均衡
> 在同一子集群内的多个实例间，BFE支持使用多种负载均衡算法：
> WRR: 加权轮询算法
> WLC: 加权最小连接数
> 
> 这个配置没找到在哪里？

参考：https://github.com/baidu/bfe/blob/develop/docs/zh_cn/configuration/server_data_conf/cluster_conf.data.md 中 BalanceMode 设置 WLC
