### ISSUE TITLE
特性咨询

### ISSUE THREAD

**Issue by solio** [baidu/bfe#137]
感谢BFE工作组的心血付出。请教两个问题：
这个版本的BFE支持灰度发布的能力吗？
还有BFE对外宣传的，WAF和GTC等特性有没有包含在这个开源版本里？
谢谢

**Comment by iyangsj** [comment]
目前，这些高级特性在BFE商业版本中提供，开源版本暂不包含。
由于一些安全考虑及开源策略，部分功能无法直接开源，未来可能基于开源生态集成实现。
