### ISSUE TITLE
扩展开发说明文档

### ISSUE THREAD

**Issue by solio** [baidu/bfe#145]
BFE应该是支持扩展开发的吧，相关的文档有么？
目前看源码，理解起来有点生硬

**Comment by iyangsj** [comment]
BFE支持扩展模块，关于扩展模块的工作机制及如何开发模块，预计在0.6.0版本文档中会详细介绍

当前，可以看简单的示范模块了解如何开发，所有扩展模块代码在 bfe_modules目录中。例如：
- bfe_modules/mod_http_code: 检查后端返回响应, 并统计状态码情况
- bfe_modules/mod_trust_clientip：判定访问用户是否来源于信任IP段

具体的问题，也可以邮件我们（bfe-osc@baidu.com) , 我们会提前详细答复。

**Comment by iyangsj** [comment]
@solio 目前已增加关于模块开发指南的文档，参见：https://github.com/baidu/bfe/blob/develop/docs/zh_cn/module/overview.md
