### ISSUE TITLE
mod_access日志问题

### ISSUE THREAD

**Issue by willzhujian** [baidu/bfe#162]
我浏览器中输入一个js路径，access日志中REQUEST_LOG打印出来，但是过了一段时间才会出闲SESSION_LOG，而且SESSION_LOG中的ses_overhead很长，看截图：这是什么问题？
![image](https://user-images.githubusercontent.com/54895023/70498981-16faeb80-1b53-11ea-8242-3392c5c2ce1a.png)

**Comment by iyangsj** [comment]
> access日志中REQUEST_LOG打印出来，但是过了一段时间才会出闲SESSION_LOG
请求日志在请求处理完成时输出；
会话日志在连接处理完成（即连接关闭）时输出

> SESSION_LOG中的ses_overhead很长
代表连接持续时间。你的场景中在连接上发送请求响应后，连接被放入浏览器连接池被未立即关闭
