### ISSUE TITLE
keepalive的生效问题和access.log的问题

### ISSUE THREAD

**Issue by solio** [baidu/bfe#178]
SESSION_LOG  2019-12-12 10:04:53 clientip: 10.32.16.5:21700 start_time: 2019-12-12 10:04:53.943085131 +0800 CST m=+9.321181909 end_time: 2019-12-12 10:04:53.968295592 +0800 CST m=+9.346392302 overhead: 25.210393ms read_total: 0 write_total: 0 keepalive_num: 1 error: CLIENT_CLOSE,EOF
bfe.conf  KeepAliveEnabled 已经设置为true
我用jmeter进行压力测试，64线程
access.log里面出现大量这样的SESSION_LOG日志，keepalive_num的数量仅为1，这代表keepalive不生效吗

**Comment by iyangsj** [comment]
> access.log里面出现大量这样的SESSION_LOG日志，keepalive_num的数量仅为1，这代表keepalive不生效吗

会话日志中 keepalive_num = 1 说明每个连接仅处理了一个请求。

可能的原因包括：
1. 客户端基于短连接发送请求
2. 客户端基于长连接发送请求，但服务端禁用HTTP KeepAlived
3. 客户端基于长连接发送请求，且服务端启用HTTP KeepAlived，但转发过程出现错误，服务端强制了关闭连接

>  bfe.conf KeepAliveEnabled 已经设置为true
> 我用jmeter进行压力测试，64线程

你看看请求日志中是否有错误，流量接入转发配置是否正确

**Comment by solio** [comment]
大部分请求是处理成功的，应该不是配置问题，
另外还有个问题转发到具体的 后端实例时，有没有使用keepalive

**Comment by solio** [comment]
![image](https://user-images.githubusercontent.com/2853620/70769243-b7474f00-1da3-11ea-9181-338ce6d2264e.png)
而且session_log和request_log是一比一的比例，但是测下来，并没有比nginx性能差很多，理论上如果都是短链接这个性能会很差，但实际上也没有很差。。。

**Comment by iyangsj** [comment]
@solio 把压测命令和使用的配置 发送至 bfe-osc@baidu.com
我们稍微邮件回复你
