### ISSUE TITLE
请教一下http2如何配置

### ISSUE THREAD

**Issue by azura27** [baidu/bfe#181]

**Comment by xiaofei0800** [comment]
可参考[tls_rule_conf.data](https://github.com/baidu/bfe/blob/develop/docs/zh_cn/configuration/tls_conf/tls_rule_conf.data.md)配置中的示例

1. 针对某些VIP启用H2协议，配置NextProtos字段。
2. 针对所有VIP启用H2协议，配置DefaultNextProtos字段。

对于方法1，需要4层负载均衡服务（可使用HAproxy，可参考[客户端双向认证中HAproxy配置示例](https://github.com/baidu/bfe/blob/develop/docs/zh_cn/example/client_auth.md)），通过PROXY协议将VIP透传给BFE。

**Comment by azura27** [comment]
谢谢，通了，感谢~~
