### ISSUE TITLE
安装时遇到个问题

### ISSUE THREAD

**Issue by gangsikunchong** [baidu/bfe#183]
go get golang.org/x/tools/cmd/goyacc
go: finding golang.org/x/tools latest
cd "bfe_basic/condition/parser" && go generate
go test -race -cover ./...
?   	github.com/baidu/bfe	[no test files]
ok  	github.com/baidu/bfe/bfe_balance	(cached)	coverage: 69.2% of statements
ok  	github.com/baidu/bfe/bfe_balance/backend	(cached)	coverage: 61.1% of statements
ok  	github.com/baidu/bfe/bfe_balance/bal_gslb	(cached)	coverage: 31.4% of statements
ok  	github.com/baidu/bfe/bfe_balance/bal_slb	(cached)	coverage: 79.6% of statements
?   	github.com/baidu/bfe/bfe_basic	[no test files]
ok  	github.com/baidu/bfe/bfe_basic/action	(cached)	coverage: 80.7% of statements
ok  	github.com/baidu/bfe/bfe_basic/condition	(cached)	coverage: 39.6% of statements
ok  	github.com/baidu/bfe/bfe_basic/condition/parser	(cached)	coverage: 47.5% of statements
ok  	github.com/baidu/bfe/bfe_bufio	(cached)	coverage: 89.3% of statements
ok  	github.com/baidu/bfe/bfe_config/bfe_cluster_conf/cluster_conf	(cached)	coverage: 64.0% of statements
ok  	github.com/baidu/bfe/bfe_config/bfe_cluster_conf/cluster_table_conf	(cached)	coverage: 36.8% of statements
ok  	github.com/baidu/bfe/bfe_config/bfe_cluster_conf/gslb_conf	(cached)	coverage: 49.1% of statements
ok  	github.com/baidu/bfe/bfe_config/bfe_conf	(cached)	coverage: 69.7% of statements
ok  	github.com/baidu/bfe/bfe_config/bfe_route_conf/host_rule_conf	(cached)	coverage: 76.8% of statements
ok  	github.com/baidu/bfe/bfe_config/bfe_route_conf/route_rule_conf	(cached)	coverage: 75.7% of statements
--- FAIL: TestVipTableLoad_2 (0.00s)
    vip_table_load_test.go:42: it should be error in VipRuleConfLoad()
FAIL
coverage: 80.6% of statements
FAIL	github.com/baidu/bfe/bfe_config/bfe_route_conf/vip_rule_conf	0.027s
?   	github.com/baidu/bfe/bfe_config/bfe_tls_conf/server_cert_conf	[no test files]
ok  	github.com/baidu/bfe/bfe_config/bfe_tls_conf/session_ticket_key_conf	(cached)	coverage: 56.2% of statements
ok  	github.com/baidu/bfe/bfe_config/bfe_tls_conf/tls_rule_conf	(cached)	coverage: 59.2% of statements
?   	github.com/baidu/bfe/bfe_debug	[no test files]
ok  	github.com/baidu/bfe/bfe_http	(cached)	coverage: 47.6% of statements
?   	github.com/baidu/bfe/bfe_http/httputil	[no test files]
ok  	github.com/baidu/bfe/bfe_http2	(cached)	coverage: 79.5% of statements
ok  	github.com/baidu/bfe/bfe_http2/hpack	(cached)	coverage: 85.6% of statements
?   	github.com/baidu/bfe/bfe_module	[no test files]
?   	github.com/baidu/bfe/bfe_modules	[no test files]
ok  	github.com/baidu/bfe/bfe_modules/mod_access	(cached)	coverage: 6.4% of statements
ok  	github.com/baidu/bfe/bfe_modules/mod_auth_basic	(cached)	coverage: 80.3% of statements
ok  	github.com/baidu/bfe/bfe_modules/mod_block	(cached)	coverage: 83.1% of statements
ok  	github.com/baidu/bfe/bfe_modules/mod_compress	(cached)	coverage: 79.3% of statements
ok  	github.com/baidu/bfe/bfe_modules/mod_errors	(cached)	coverage: 11.4% of statements
ok  	github.com/baidu/bfe/bfe_modules/mod_geo	(cached)	coverage: 78.8% of statements
ok  	github.com/baidu/bfe/bfe_modules/mod_header	(cached)	coverage: 54.9% of statements
ok  	github.com/baidu/bfe/bfe_modules/mod_http_code	(cached)	coverage: 64.3% of statements
?   	github.com/baidu/bfe/bfe_modules/mod_key_log	[no test files]
?   	github.com/baidu/bfe/bfe_modules/mod_logid	[no test files]
ok  	github.com/baidu/bfe/bfe_modules/mod_redirect	(cached)	coverage: 81.2% of statements
ok  	github.com/baidu/bfe/bfe_modules/mod_rewrite	(cached)	coverage: 58.6% of statements
ok  	github.com/baidu/bfe/bfe_modules/mod_static	(cached)	coverage: 76.0% of statements
ok  	github.com/baidu/bfe/bfe_modules/mod_trust_clientip	(cached)	coverage: 65.0% of statements
ok  	github.com/baidu/bfe/bfe_net/textproto	(cached)	coverage: 71.0% of statements
ok  	github.com/baidu/bfe/bfe_proxy	(cached)	coverage: 89.2% of statements
ok  	github.com/baidu/bfe/bfe_route	(cached)	coverage: 11.9% of statements
?   	github.com/baidu/bfe/bfe_route/bfe_cluster	[no test files]
ok  	github.com/baidu/bfe/bfe_route/trie	(cached)	coverage: 96.4% of statements
ok  	github.com/baidu/bfe/bfe_server	(cached)	coverage: 0.1% of statements
ok  	github.com/baidu/bfe/bfe_spdy	(cached)	coverage: 77.9% of statements
ok  	github.com/baidu/bfe/bfe_stream	(cached)	coverage: 90.8% of statements
ok  	github.com/baidu/bfe/bfe_tls	(cached)	coverage: 77.8% of statements
ok  	github.com/baidu/bfe/bfe_util	(cached)	coverage: 11.6% of statements
?   	github.com/baidu/bfe/bfe_util/access_log	[no test files]
ok  	github.com/baidu/bfe/bfe_util/bns	(cached)	coverage: 66.7% of statements
ok  	github.com/baidu/bfe/bfe_util/byte_pool	(cached)	coverage: 100.0% of statements
ok  	github.com/baidu/bfe/bfe_util/hash_set	(cached)	coverage: 90.6% of statements
ok  	github.com/baidu/bfe/bfe_util/ipdict	(cached)	coverage: 87.6% of statements
ok  	github.com/baidu/bfe/bfe_util/ipdict/txt_load	(cached)	coverage: 81.8% of statements
ok  	github.com/baidu/bfe/bfe_util/net_util	(cached)	coverage: 37.4% of statements
ok  	github.com/baidu/bfe/bfe_util/pipe	(cached)	coverage: 66.7% of statements
ok  	github.com/baidu/bfe/bfe_util/signal_table	(cached)	coverage: 31.2% of statements
ok  	github.com/baidu/bfe/bfe_websocket	(cached)	coverage: 86.0% of statements
FAIL
make: *** [test-case] Error 1

**Comment by iyangsj** [comment]
感谢反馈！如果方便请点击加入 https://bfe-networks.slack.com/messages/bfeuser 以便在线交流复现及解决遇到的问题

**Comment by gangsikunchong** [comment]
> 问题已知悉，感谢反馈！
> 如果方便请提供如下补充信息，包括操作系统、golang版本、复现方式。

mac os 10.13.6，go version go1.13.4 darwin/amd64,就下载下来运行了make

**Comment by Galvin-wjw** [comment]
一些依赖被墙了？
之前大陆服务器一直测试不过，
换了个香港的机器可以了

**Comment by iyangsj** [comment]
感谢反馈！在 #259 中已解决
