### ISSUE TITLE
Performance of BFE request processing

### ISSUE THREAD

**Issue by wangfakang** [baidu/bfe#192]
Please ask,  the current version of TFE's ability to handle requests been compared with Nginx? Such as    keepalive-connection , nokeepalive-connection or reverse proxy etc scenario.    thx

**Comment by iyangsj** [comment]
后续版本的文档中会提供性能测试章节内容，欢迎关注。
也欢迎反馈实际场景性能测试相关问题。

**Comment by JesseLiiu** [comment]
同样对 BFE 的性能数据感兴趣。
在新版本的文档中，没有看到性能对比。 nginx 目前处理 http 请求的 QPS 应该 >1.25w/s 单核。
