### ISSUE TITLE
性能瓶颈测试发现性能低于预想，想请教一下测试方法

### ISSUE THREAD

**Issue by azura27** [baidu/bfe#194]
您好，我这边在用wrk测试BFE的性能的时候，发现性能仅达到Nginx性能的1/8左右
在这里我是通过QPS参数作为性能标志的，方法：压测4轮，每次30秒，取出最大QPS值
测试环境如下：测试机器均在北京
BFE所在机房：万兆网卡，物理机32core。
模拟客户端机器IP：6 台物理机 
模拟后台服务器机器：2台物理机 
BFE和客户端机器所在机房间延时小于1.5ms

BFE在这里会转发到两台后台服务器（http & https），后台服务器安装有Nginx，进行静态页面显示，文件大小为1024byte和4096byte两种

请问这有什么问题吗？或者最优的测试方法是什么呢？

**Comment by iyangsj** [comment]
感谢反馈！测试结果与典型场景真实流量性能数据相差较大。欢迎加入slack与我们进一步在线讨论。

https://join.slack.com/t/bfe-networks/shared_invite/enQtODc2NTIyMjI0NzU2LTgzOTJkMjQ3ZTJkMzQwNzYxZjIyM2ZkMTJkZDYwNmRlZmYzODMxNzdhN2UxYzE0ZjIwN2Q1NmY2ZGM2YjUxOGI
（点击按提示操作）
