### ISSUE TITLE
 mod_static: allow sending precompressed files instead of regular files

### ISSUE THREAD

**Issue by iyangsj** [baidu/bfe#199]
**Description**:
If the client support gzip:
- to service a request for a file (eg. /path/to/a.html),  try to find and send compressed version of the file (with the “.gz” filename extension, eg. /path/to/a.html.gz)
- If the file doesn’t exist,  sends the uncompressed version of the file.

**Reference**:
Add option ConfModStatic.Basic.EnableCompression

**Comment by u5surf** [comment]
@iyangsj 
Hi, I’ll catch up on this issue. if the req.HttpRequest contains the http header of `Accept-Encoding: gzip`, we can return the gzip compressed contents.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding

**Comment by iyangsj** [comment]
> Hi, I’ll catch up on this issue.

We sincerely appreciate your contribution.
