### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by ztf214** [baidu/bfe#203]
$ make
go get golang.org/x/tools/cmd/goyacc
go: finding golang.org/x/tools latest
go: downloading golang.org/x/tools v0.0.0-20191227053925-7b8e75db28f4
go: extracting golang.org/x/tools v0.0.0-20191227053925-7b8e75db28f4
go: downloading golang.org/x/tools v0.0.0-20191210221141-98df12377212
go: extracting golang.org/x/tools v0.0.0-20191210221141-98df12377212
cd "bfe_basic/condition/parser" && go generate
go test -race -cover ./...
go test: -race is only supported on linux/amd64, linux/ppc64le, linux/arm64, freebsd/amd64, netbsd/amd64, darwin/amd64 and windows/amd64
make: *** [Makefile:56: test-case] Error 2

**Comment by iyangsj** [comment]
建议在Linux环境开发或使用，其它系统暂不支持。

**Comment by ztf214** [comment]
多谢指点------------------ 原始邮件 ------------------
发件人: "Sijie Yang"<notifications@github.com>
发送时间: 2019年12月29日(星期天) 晚上7:26
收件人: "baidu/bfe"<bfe@noreply.github.com>;
抄送: "ztf214"<1443393629@qq.com>;"Manual"<manual@noreply.github.com>;
主题: Re: [baidu/bfe] 请教一下 (#203)



建议在Linux环境开发或使用，其它系统暂不支持。
 
&mdash;
