### ISSUE TITLE
执行make时遇到问题

### ISSUE THREAD

**Issue by ztf214** [baidu/bfe#208]
go: finding github.com/pquerna/ffjson v0.0.0-20190930134022-aa0246cd15f7
go: finding github.com/asergeyev/nradix v0.0.0-20170505151046-3872ab85bb56
go: finding github.com/abbot/go-http-auth v0.4.1-0.20181019201920-860ed7f246ff
go: finding github.com/spaolacci/murmur3 v1.1.0
go: finding github.com/zmap/go-iptree v0.0.0-20170831022036-1948b1097e25
go: finding gopkg.in/warnings.v0 v0.1.2
go: finding gopkg.in/gcfg.v1 v1.2.3
go: finding github.com/oschwald/geoip2-golang v1.3.0
go: finding github.com/gomodule/redigo v2.0.0+incompatible
go: finding github.com/baidu/go-lib v0.0.0-20191211084149-f80a8a568e3f
go: finding github.com/oschwald/maxminddb-golang v1.5.0
go: finding github.com/jehiah/go-strftime v0.0.0-20171201141054-1d33003b3869
go: golang.org/x/net@v0.0.0-20191209160850-c0dbc17a3553: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: connect: connection refused)
go: golang.org/x/crypto@v0.0.0-20191206172530-e9b2fee46413: unrecognized import path "golang.org/x/crypto" (https fetch: Get https://golang.org/x/crypto?go-get=1: dial tcp 216.239.37.1:443: connect: connection refused)
go: golang.org/x/tools@v0.0.0-20191210221141-98df12377212: unrecognized import path "golang.org/x/tools" (https fetch: Get https://golang.org/x/tools?go-get=1: dial tcp 216.239.37.1:443: connect: connection refused)
go: golang.org/x/sys@v0.0.0-20191210023423-ac6580df4449: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: connect: connection refused)
go: error loading module requirements
go get golang.org/x/tools/cmd/goyacc
go: golang.org/x/crypto@v0.0.0-20191206172530-e9b2fee46413: unrecognized import path "golang.org/x/crypto" (https fetch: Get https://golang.org/x/crypto?go-get=1: dial tcp 216.239.37.1:443: connect: connection refused)
go: golang.org/x/sys@v0.0.0-20191210023423-ac6580df4449: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: connect: connection refused)
go: golang.org/x/tools@v0.0.0-20191210221141-98df12377212: unrecognized import path "golang.org/x/tools" (https fetch: Get https://golang.org/x/tools?go-get=1: dial tcp 216.239.37.1:443: connect: connection refused)
go: golang.org/x/net@v0.0.0-20191209160850-c0dbc17a3553: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: connect: connection refused)
go: error loading module requirements
Makefile:44: recipe for target 'prepare-dep' failed
make: *** [prepare-dep] Error 1

**Comment by iyangsj** [comment]
你的环境无法访问golang.org, 建议先设置代理：
export GOPROXY=https://goproxy.io

**Comment by ztf214** [comment]
好的谢谢



---原始邮件---
发件人: "Sijie Yang"<notifications@github.com&gt;
发送时间: 2020年1月6日(周一) 下午5:10
收件人: "baidu/bfe"<bfe@noreply.github.com&gt;;
抄送: "ztf214"<1443393629@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [baidu/bfe] 执行make时遇到问题 (#208)



你的环境无法访问golang.org, 建议先设置代理：
 export GOPROXY=https://goproxy.io
