### ISSUE TITLE
咨询下这个开源的bfe中是否包含gtc的外网调度能力？

### ISSUE THREAD

**Issue by coder081** [baidu/bfe#28]
之前在一些介绍材料中了解到BFE除了本身组件外，还有两个核心的调度组件，一个GSLB，另外一个GTC组件，这个开源的版本中，GTC外网调度能力是否包含？

**Comment by iyangsj** [comment]
开源BFE目前的版本不包含GTC/GSLB。有兴趣可以体验GTC的公有云版本：https://cloud.baidu.com/product/itm.html

**Comment by coder081** [comment]
多谢，我去公有云上去了解下；
另外，这个开源版本中，有包含“安全攻防”以及“数据分析”两个子特性吗？
还是说，这个开源版本当前主要开源的特性，就是接入和转发能力？

**Comment by anlinsa** [comment]
据我了解目前的版本里安全和数据的特性没有的
