### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by ztf214** [baidu/bfe#282]
请问关于使用示例中的分流转发场景，如何知道是否转发成功，在moniter中是否有体现

**Comment by ztf214** [comment]
今天启动时又报了这样的错，麻烦您帮看下
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x701d25]

goroutine 1 [running]:
github.com/baidu/bfe/bfe_route/bfe_cluster.(*BfeCluster).BasicInit(0xc0000c0880, 0x0, 0xc000191840, 0x0, 0x0)
    /home/zhengtf/gocode/src/github.com/baidu/bfe/bfe_route/bfe_cluster/bfe_cluster.go:65 +0x55
github.com/baidu/bfe/bfe_route.(*ClusterTable).BasicInit(0xc0001dcb80, 0xc0001d3430, 0xc000010998)
    /home/zhengtf/gocode/src/github.com/baidu/bfe/bfe_route/cluster_table.go:69 +0x15d
github.com/baidu/bfe/bfe_route.(*ClusterTable).Init(0xc0001dcb80, 0xc00002b500, 0x2a, 0x0, 0xc000181e00)
    /home/zhengtf/gocode/src/github.com/baidu/bfe/bfe_route/cluster_table.go:55 +0x9e
github.com/baidu/bfe/bfe_route.(*ServerDataConf).clusterTableLoad(0xc0001d2b90, 0xc00002b500, 0x2a, 0xc00002b470, 0x26)
    /home/zhengtf/gocode/src/github.com/baidu/bfe/bfe_route/server_data_conf.go:100 +0x47
github.com/baidu/bfe/bfe_route.LoadServerDataConf(0xc00002b440, 0x27, 0xc00002b470, 0x26, 0xc00002b4a0, 0x28, 0xc00002b500, 0x2a, 0x30, 0xa3a260, ...)
    /home/zhengtf/gocode/src/github.com/baidu/bfe/bfe_route/server_data_conf.go:59 +0x210
github.com/baidu/bfe/bfe_server.(*BfeServer).InitDataLoad(0xc00014e700, 0x0, 0x0)
    /home/zhengtf/gocode/src/github.com/baidu/bfe/bfe_server/bfe_confdata_load.go:42 +0x9b
github.com/baidu/bfe/bfe_server.StartUp(0x1f90, 0x20fb, 0x20e5, 0x1, 0xa8f7f3, 0x3, 0x1e, 0x3c, 0x3c, 0xa, ...)
    /home/zhengtf/gocode/src/github.com/baidu/bfe/bfe_server/bfe_server_init.go:62 +0x16e
main.main()
    /home/zhengtf/gocode/src/github.com/baidu/bfe/bfe.go:101 +0x40b

**Comment by iyangsj** [comment]
>> 请问关于使用示例中的分流转发场景，如何知道是否转发成功，在moniter中是否有体现

发送测试请求，检查访问日志或监控指标

**方式一：比较测试请求响应**
发送测试请求，比较以下两种场景响应是否一致：
- 向后端实例直接发送请求
- 向BFE发送测试请求（由BFE转发至后端）

**方式二：检查后端返回码统计信息**
注：需启用mod_http_code模块，并查看 http://<ADDR>/monitor/mod_http_code 

配置方式参考： https://github.com/baidu/bfe/blob/develop/docs/zh_cn/configuration/mod_http_code/mod_http_code.md

查看监控指标：
https://github.com/baidu/bfe/blob/develop/docs/zh_cn/monitor.md

监控指标说明
https://github.com/baidu/bfe/blob/develop/docs/zh_cn/monitor/mod_http_code.md

**方式三：查看访问日志，检查日志相关字段**
字段包括：错误类型(error)、后端实例信息(serverip)、响应码(status)

注：需启用mod_access模块
配置方式参考:https://github.com/baidu/bfe/blob/develop/docs/zh_cn/configuration/mod_access/mod_access.md

**Comment by iyangsj** [comment]
>> 今天启动时又报了这样的错，麻烦您帮看下
感谢反馈，请将程序及配置压缩打包，发送至 bfe-osc@baidu.com
我们会在工作日尽快答复 @ztf214

**Comment by iyangsj** [comment]
>> 今天启动时又报了这样的错，麻烦您帮看下
@ztf214 问题在 v0.9.0 版本已修复 #382
