### ISSUE TITLE
现有的扩展module可以支持域名级别配置吗？

### ISSUE THREAD

**Issue by Q-Zhan** [baidu/bfe#284]
看了下代码，module使用后貌似都是全局生效的，可以针对某个域名配置module吗

**Comment by iyangsj** [comment]
@Q-Zhan 绝大部分module包含了规则配置文件，可以在其中的规则条件中指定对某个域名生效。

例如：基于mod_block(黑名单封禁模块) 封禁某个域名的请求，可在mod_block的规则条件中指定条件 req_host_in("example.com") 
(参见：https://github.com/baidu/bfe/blob/develop/docs/zh_cn/example/block.md）

**Comment by Q-Zhan** [comment]
@iyangsj 那么如果全局配置了mod_block模块，是不是每次请求进来都会去判断是否能匹配上mod_block的规则配置？这样全局配置的模块数量多了后是否对性能有所损耗呢？

**Comment by iyangsj** [comment]
@Q-Zhan 不是每个请求都需要去判断（仅对应产品线的请求）
