### ISSUE TITLE
咨询负载均衡算法配置

### ISSUE THREAD

**Issue by ztf214** [baidu/bfe#293]
func (brr *BalanceRR) Balance(algor int, key []byte) (*backend.BfeBackend, error) {

	switch algor {

	case WrrSimple:

		return brr.simpleBalance()

	case WrrSmooth:

		return brr.smoothBalance()

	case WrrSticky:

		return brr.stickyBalance(key)

	case WlcSimple:

		return brr.leastConnsSimpleBalance()

	case WlcSmooth:

		return brr.leastConnsSmoothBalance()

	default:

		return brr.smoothBalance()

	}

}
请问对于这五种算法的选择要在哪个配置文件中设置

**Comment by iyangsj** [comment]
负载均衡算法的配置见  https://github.com/baidu/bfe/blob/develop/docs/zh_cn/configuration/server_data_conf/cluster_conf.data.md 中配置项BalanceMode 

注意：这五种算法中部分仅用于单元测试中比较性能，不推荐使用且无法再配置文件中启用

**Comment by ztf214** [comment]
请问BFE可否动态监控后端服务器的各项性能数据

**Comment by iyangsj** [comment]
感谢关注，内部BFE版本基于访问日志实时统计实现（延迟、吞吐、成功率等），开源BFE版本暂不支持 @ztf214
