### ISSUE TITLE
https://github.com/baidu/bfe/blob/develop/docs/zh_cn/SUMMARY.md 这个页面的一些链接错了哦

### ISSUE THREAD

**Issue by acyouzi** [baidu/bfe#3]
![image](https://user-images.githubusercontent.com/11007732/62687228-eebe7d00-b9f8-11e9-870a-7c189cdd2764.png)

https://github.com/baidu/bfe/blob/develop/docs/zh_cn/bfe_config/bfe.conf.md => https://github.com/baidu/bfe/blob/develop/docs/zh_cn/configuration/bfe.conf.md

**Comment by iyangsj** [comment]
感谢你的提醒，我们会尽快更新!
