### ISSUE TITLE
请问模块测试文件如何使用

### ISSUE THREAD

**Issue by ztf214** [baidu/bfe#308]
![$VI257~ON(K2V6IU$}WPUVH](https://user-images.githubusercontent.com/59257751/77766610-d92ac000-707a-11ea-8b09-0280248ff43a.png)

**Comment by iyangsj** [comment]
可运行make test运行单元测试。参见文档说明：https://github.com/baidu/bfe/blob/develop/docs/en_us/install.md#build-from-source
