### ISSUE TITLE
现有开源项目是否支持GSLB 跨IDC机房集群流量分流控制

### ISSUE THREAD

**Issue by zjw940419** [baidu/bfe#34]
目前开源版本我已验证本机房多个子集群间数据分流，那么现有开源项目是否支持GSLB 跨IDC机房集群流量分流控制？

**Comment by iyangsj** [comment]
目前开源版本支持GSLB，GSLB分流比例配置参见https://github.com/baidu/bfe/blob/develop/docs/zh_cn/configuration/cluster_conf/gslb.data.md

**Comment by zjw940419** [comment]
嗯嗯，我了解到相关资料，BFE中GSLB具有自动分配容量的能力，目前只看到了GSLB分流比例配置，也就是说A子集群1分配50%，A子集群2分配50%，但此时A1子集群负载高了，是否会缩小分配的比例，同时流量分发是基于全局流量还是bfe单点流量分发的？

**Comment by iyangsj** [comment]
GSLB自动模式未包含在当前开源版本中（注：在自动模式下，将基于后端容量、内网距离及连通性、到达BFE流量，自动计算并调整GSLB分流比例）

**Comment by zjw940419** [comment]
OK，了解了，多谢！
