### ISSUE TITLE
readrequest_test.go error

### ISSUE THREAD

**Issue by macotutu** [baidu/bfe#364]
**Describe the bug**
readrequest_test.go can't pass of two test cases, because of the double quotation marks misstion

**To Reproduce**
when run the make command, it will not pass, and report the error
```
--- FAIL: TestReadRequest (0.00s)
    readrequest_test.go:344: #3: error "parse \"../../../../etc/passwd\": invalid URI for request", want error "parse ../../../../etc/passwd: invalid URI for request"
    readrequest_test.go:344: #4: error "parse \"\": empty url", want error "parse : empty url"
FAIL
```
**Expected behavior**
Fix the bug by add the miss double quotation marks

**Screenshots**
![image](https://user-images.githubusercontent.com/12167740/78322634-e592a980-75a1-11ea-9256-e320d92c0419.png)

**Additional context**

**Comment by iyangsj** [comment]
@macotutu 感谢你对反馈！请提供下复现问题的环境：操作系统、golang版本

**Comment by macotutu** [comment]
在以下2个环境下都有这个问题:
    操作系统: CentOS6
    golang版本: 1.14

    操作系统: Mac OSX 10.14.5
    golang版本: 1.14

**Comment by macotutu** [comment]
> @macotutu 感谢你的反馈！请提供下复现问题的环境：操作系统、golang版本



> > @macotutu 感谢你的反馈！请提供下复现问题的环境：操作系统、golang版本
> 
> 在以下2个环境下都有这个问题:
> 
> ```
> 操作系统: CentOS6
> golang版本: 1.14
> 
> 操作系统: Mac OSX 10.14.5
> golang版本: 1.14
> ```

![image](https://user-images.githubusercontent.com/12167740/78338991-5481f980-75c6-11ea-8135-014c59919e50.png)

我做了修改后就可以通过了.

本来想给你们提PR的, 但是按PR提交规范提交修改的时候, `go vet` 失败了

**Comment by iyangsj** [comment]
@macotutu 感谢提供的反馈！

>> 我做了修改后就可以通过了
go 1.14 中net/url 升级导致解析uri错误信息变化。你的修复方案会导致在go1.13版本编译失败

建议的修改方式：
1. 单元测试用例中只保留错误关键字符串 （例：invalid URI for request / empty url)
2. 单元测试中，将错误字符串相等检查，改为字符串包含检查
https://github.com/baidu/bfe/blob/develop/bfe_http/readrequest_test.go#L343

>> 按PR提交规范提交修改的时候, go vet 失败了
临时方式：git commit 增加-n参数提交

**Comment by macotutu** [comment]
> @macotutu 感谢提供的反馈！
> 
> 
> 
> >> 我做了修改后就可以通过了
> 
> 
> 
> go 1.14 中net/url 升级导致解析uri错误信息变化。你的修复方案会导致在go1.13版本编译失败
> 
> 
> 
> 建议的修改方式：
> 
> 1. 单元测试用例中只保留错误关键字符串 （例：invalid URI for request / empty url)
> 
> 2. 单元测试中，将错误字符串相等检查，改为字符串包含检查
> 

原来如此哈，那我安装你的建议修改下哈

**Comment by iyangsj** [comment]
#370
