### ISSUE TITLE
开源版本是否包含轮转GC

### ISSUE THREAD

**Issue by silentred** [baidu/bfe#523]
记得BFE有分享过为了减少GC带来的服务延时，手动关闭GC, 使用多进程轮转GC的方式提供服务。这个功能是否在开源版本中？

**Comment by iyangsj** [comment]
Duplicate of #108

**Comment by iyangsj** [comment]
@silentred 参考这个issue： https://github.com/baidu/bfe/issues/108

**Comment by silentred** [comment]
@iyangsj 多谢
