### ISSUE TITLE
这也没有一个可用的文档或者daemon学习?

### ISSUE THREAD

**Issue by R1hug0** [baidu/bfe#90]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

好歹给点使用文档和范例呀

**Comment by iyangsj** [comment]
- 中文文档目录：https://github.com/baidu/bfe/blob/develop/docs/zh_cn/SUMMARY.md
- 安装说明：https://github.com/baidu/bfe/blob/develop/docs/zh_cn/install.md
- 使用示例：https://github.com/baidu/bfe/blob/develop/docs/zh_cn/SUMMARY.md 中使用示例 章节

如果遇到其它问题欢迎反馈
