### ISSUE TITLE
not support tcp proxy?

### ISSUE THREAD

**Issue by flyzhang007** [baidu/bfe#91]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by iyangsj** [comment]
感谢关注！网络技术生态中有非常优秀的四层负载均衡项目来满足这个需求，开源BFE的核心定位依然是七层。（注： BFE私有化相关产品，提供了完整的网络接入解决方案）
